version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: event-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: event_booking
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    container_name: event-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: event_booking

volumes:
  db_data: